GestionReservas.Data/GestionReservas.UI/Controllers/ClienteController.cs
using GestionReservas.Data;
using GestionReservas.Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionReservas.UI.Controllers
{
    public class ClienteController : Controller
    {
        ClienteNegocio _cliente;

        public ClienteController()
        {
            if (_cliente == null)
                _cliente = new ClienteNegocio();
        }

        // GET: Default
        public ActionResult Index()
        {
            ViewBag.listar = _cliente.ListarCliente(null);
            return View();
        }

        // GET: Default/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            Cliente cliente = new Cliente();
            cliente.Nombre = collection[1];
            cliente.NumeroIdentificacion = collection[2];
            cliente.SaldoActual = Convert.ToDouble(collection[3]);
            cliente.Telefono = collection[4];

            try
            {
                // TODO: Add insert logic here

                _cliente.GuardarActualizarCliente(cliente);
               return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionReservas.Data/GestionReservas.UI/Controllers/ReservacionController.cs
using GestionReservas.Data;
using GestionReservas.Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionReservas.UI.Controllers
{
    public class ReservacionController : Controller
    {
        ReservasNegocio _reserva;
        SalaNegocio _salon;
        ClienteNegocio _cliente;

        public ReservacionController()
        {
            if (_reserva == null)
                _reserva = new ReservasNegocio();
            if (_cliente == null)
                _cliente = new ClienteNegocio();
            if (_salon == null)
                _salon = new SalaNegocio();
        }

        // GET: Reservacion
        public ActionResult Index()
        {
            ViewBag.listar = _reserva.ListarReservacion(null);
            return View();
        }

        // GET: Reservacion
        public ActionResult Confirmar()
        {
            ViewBag.listar = _reserva.ListarReservacionSinConfirmar();
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult ConfirmarPost(int idReserva)
        {
            Reservacion reserva = _reserva.BuscarReservaXId(idReserva);
            reserva.Confimada = true;
            _reserva.GuardarActualizarReservacion(reserva);

            ViewBag.listar = _reserva.ListarReservacionSinConfirmar();
            return View();
        }

        // GET: Reservacion
        public ActionResult Pagar()
        {
            ViewBag.listar = _reserva.ListarReservacionSinPagar();
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult PagarPost(int idReserva)
        {
            Reservacion reserva = _reserva.BuscarReservaXId(idReserva);
            reserva.Paga = true;
            _reserva.GuardarActualizarReservacion(reserva);

            ViewBag.listar = _reserva.ListarReservacionSinPagar();
            return View();
        }


        // GET: Default/Details/5
        public ActionResult Details(int id)
        {
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            ViewBag.Paga = false;
            ViewBag.Confirmar = false;
            ViewBag.Cliente = _cliente.ListarCliente(null);
            ViewBag.Salon = _salon.ListarSala(null);
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            Reservacion reserva = new Reservacion();
            reserva.HoraInicio = collection[1];
            reserva.HoraFin = collection[2];
            //reserva.Paga = Convert.ToBoolean(collection[3]);
            //reserva.Confimada = Convert.ToBoolean(collection[4]);
            reserva.Valor = Convert.ToDouble(collection[3]);
            reserva.IdSalon = Convert.ToInt32(collection[4]);
            reserva.IdCliente = Convert.ToInt32(collection[5]);



            try
            {
                // TODO: Add insert logic here

                _reserva.GuardarActualizarReservacion(reserva);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Reservacion
        public ActionResult ReportePendientesPago()
        {
            ViewBag.listar = _reserva.ListarReservacionSinPagar();
            return View();
        }

        // GET: Reservacion
        public ActionResult ReportePendientesConfimacion()
        {
            ViewBag.listar = _reserva.ListarReservacionSinConfirmar();
            return View();
        }
        

        // GET: Reservacion
        public ActionResult ReservasCliente()
        {
            ViewBag.Cliente = _cliente.ListarCliente(null);
            ViewBag.listar = _reserva.BuscarReservaXIdCliente(0);
            return View();
        }

        // POST: Reservacion
        public ActionResult ReservasClientePost(int idCliente)
        {
            ViewBag.listar = _reserva.BuscarReservaXIdCliente(idCliente);
            return View();
        }
    }
}

GestionReservas.Data/GestionReservas.UI/Controllers/SalaController.cs
using GestionReservas.Data;
using GestionReservas.Negocio;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace GestionReservas.UI.Controllers
{
    public class SalaController : Controller
    {
        SalaNegocio _sala;
        ComunesNegocio _comunes;


        public SalaController()
        {
            if (_sala == null)
                _sala = new SalaNegocio();
            if (_comunes == null)
                _comunes = new ComunesNegocio();
        }

        // GET: Sala
        public ActionResult Index()
        {
            ViewBag.listar = _sala.ListarSala(null);
            return View();
        }

        // GET: Default/Create
        public ActionResult Create()
        {
            ViewBag.TipoEspacio = _comunes.ListarEspacios();
            ViewBag.Cualidades = _comunes.ListarTipoCualidades();
            return View();
        }

        // POST: Default/Create
        [HttpPost]
        public ActionResult Create(FormCollection collection)
        {
            Sala sala = new Sala();
            sala.Nombre = collection[1];
            sala.Descripcion = collection[2];
            sala.Precio = Convert.ToDouble(collection[3]);
            sala.IdTipoEspacio= Convert.ToInt32(collection[4]);
            sala.IdCualidades= Convert.ToInt32(collection[5]);
           
            try
            {
                // TODO: Add insert logic here

                _sala.GuardarActualizarSala(sala);
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                return View();
            }
        }

        // GET: Default/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Default/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Default/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Default/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

GestionReservas.Data/GestionReservas.UI/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")


    @* First try loading jQuery from Google's CDN*@
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>


</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Gestion de Reservas", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    @*<li>@Html.ActionLink("Home", "Index", "Home")</li>
                        <li>@Html.ActionLink("About", "About", "Home")</li>
                        <li>@Html.ActionLink("Contact", "Contact", "Home")</li>*@


                   
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Cliente
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("Index", "Cliente")">Listar</a>
                            <a class="dropdown-item" href="@Url.Action("Create", "Cliente")">Crear</a>
                        </div>
                    </li>


                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Salon
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("Index", "Sala")">Listar</a>
                            <a class="dropdown-item" href="@Url.Action("Create", "Sala")">Crear</a>
                        </div>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reserva
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("Index", "Reservacion")">Listar</a>
                            <a class="dropdown-item" href="@Url.Action("Create", "Reservacion")">Crear</a>
                            <a class="dropdown-item" href="@Url.Action("Confirmar", "Reservacion")">Confirmar</a>
                            <a class="dropdown-item" href="@Url.Action("Pagar", "Reservacion")">Pagar</a>
                        </div>
                    </li>



                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Reportes
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                            <a class="dropdown-item" href="@Url.Action("ReservasCliente", "Reservacion")">Reservas por cliente</a>
                            <a class="dropdown-item" href="@Url.Action("ReportePendientesConfimacion", "Reservacion")">Reservas pendientes por confirmar</a>
                            <a class="dropdown-item" href="@Url.Action("ReportePendientesPago", "Reservacion")">Reservas pendientes por pagar</a>
                        </div>
                    </li>


                </ul>
                @Html.Partial("_LoginPartial")
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>